In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np
from math import *

In [27]:
# function calculating the euclidean distance from the basket which is centered at (0,0)
def distance(x, y):
    distances = np.sqrt(np.square(x) + np.square(y))
    return distances
    
# function determining whether a field-goal is a 3-pointer: 0 is a 2 pointer, 1 is a non-corner 3-pointer, 2 is a corner 3
def classification(data):
        x, y = data.x, data.y
        distances = distance(x,y)
        data["distances"] = distances
        corner = y>7.8
        cl = np.zeros(len(x))
        for i,j in enumerate(corner,0):
            if j:
                if distances[i] >=23.75:
                    cl[i] = 1
                else:
                    cl[i] = 0
            else:
                if distances[i] >= 22:
                    cl[i] = 2
                else:
                    cl[i] = 0
        data['classification'] = cl
        return data
    
# assigns 1 for a field goal if it is a 3 and 0 if not        
def three_pointer_made(data):
    data = data[data.classification >=1]
    total = np.sum(data.fgmade)
    return total

# calculates the percentage of shots attempted in a zone
def zone_percentage(zone, data, fga):
    category = (data['classification'] == zone).astype(int)
    return round(np.sum(category) /fga * 100, 3)

#calculates the total effective field goal percentage for a team
def total_efg(data, fga):
        fgm = np.sum(data['fgmade'])
        three_pm = three_pointer_made(data)
        return round((fgm+(0.5*three_pm))/fga * 100, 3)

#calculates the effective field goal percentage for a zone
def efg_zone(data, zone):
    data = data[data["classification"]==zone]
    fga = data.shape[0]
    return total_efg(data,fga)

In [3]:
# importing data set into notebook, 
shots_data = pd.read_csv("./utility/shots_data.csv")
shots_data

       team     x     y  fgmade
0    Team A -23.1   3.5       0
1    Team A   0.0  25.1       1
2    Team A   0.5   1.0       1
3    Team A  -5.6   5.2       0
4    Team A   4.0  14.5       1
..      ...   ...   ...     ...
555  Team B   7.8  24.7       0
556  Team B  10.1   1.4       1
557  Team B -17.8  -0.1       0
558  Team B  22.6   2.9       0
559  Team B  -0.7  14.7       1

[560 rows x 4 columns]

In [4]:
# copy of data for distribution of shots, maybe used later
data_a = shots_data.copy()

In [5]:
shots_data.describe()

                x           y      fgmade
count  560.000000  560.000000  560.000000
mean     1.049821   11.156071    0.392857
std     11.074739    9.487093    0.488822
min    -23.600000   -1.500000    0.000000
25%     -4.250000    2.000000    0.000000
50%      0.600000    8.500000    0.000000
75%      7.475000   20.725000    1.000000
max     23.800000   29.700000    1.000000

Shot Distribution Section

In [6]:
# add a column to the data frame representing classification of each shot (function above)
classification(shots_data)
shots_data.describe()

                x           y      fgmade   distances  classification
count  560.000000  560.000000  560.000000  560.000000      560.000000
mean     1.049821   11.156071    0.392857   15.436219        0.478571
std     11.074739    9.487093    0.488822    9.986809        0.629824
min    -23.600000   -1.500000    0.000000    0.223607        0.000000
25%     -4.250000    2.000000    0.000000    3.915344        0.000000
50%      0.600000    8.500000    0.000000   18.122634        0.000000
75%      7.475000   20.725000    1.000000   25.322667        1.000000
max     23.800000   29.700000    1.000000   29.917386        2.000000

In [7]:
# seperating data into Team A and B
teams = shots_data.groupby(shots_data.team)
team_a = teams.get_group('Team A')
team_b = teams.get_group('Team B')
fga_teama = team_a.shape[0]
fga_teamb = team_b.shape[0]

In [28]:
zones = [0, 1, 2]
zone_names = ["2PT", "NC3", "C3"]
print("For Team A the shot distribution is given below:\n")
for i,j in enumerate(zones, 0):
    print("Field goals attempted in the " + str(zone_names[i]) + " zone is " + str(zone_percentage(j,team_a, fga_teama)) + "%\n")


print("For Team B the shot distribution is given below:\n")
for i,j in enumerate(zones, 0):
    print("Field goals attempted in the " + str(zone_names[i]) + " zone is " + str(zone_percentage(j,team_b, fga_teamb)) + "%\n")

For Team A the shot distribution is given below:

Field goals attempted in the 2PT zone is 60.714%

Field goals attempted in the NC3 zone is 32.143%

Field goals attempted in the C3 zone is 7.143%

For Team B the shot distribution is given below:

Field goals attempted in the 2PT zone is 58.214%

Field goals attempted in the NC3 zone is 34.286%

Field goals attempted in the C3 zone is 7.5%

Effective Field Goal Percentage

In [29]:
# finding both teams total effective field goal percentage
print("The total effective field goal percentage for team A was " + str(total_efg(team_a,fga_teama)) + "%\n")
print("The total effective field goal percentage for team B was " + str(total_efg(team_b,fga_teamb)) + "%\n")

The total effective field goal percentage for team A was 44.107%

The total effective field goal percentage for team B was 48.214%

In [30]:
# finding effective field goal percentage by zone
zones = [0, 1, 2]
zone_names = ["2PT", "NC3", "C3"]
for i,j in enumerate(zones):
    print("The effective field percentage of Team A in the " + str(zone_names[i]) + " zone was " + str(efg_zone(team_a,j)) + "%\n")
for i,j in enumerate(zones):
    print("The effective field percentage of Team B in the " + str(zone_names[i]) + " zone was " + str(efg_zone(team_b,j)) + "%\n")

The effective field percentage of Team A in the 2PT zone was 40.0%

The effective field percentage of Team A in the NC3 zone was 48.333%

The effective field percentage of Team A in the C3 zone was 60.0%

The effective field percentage of Team B in the 2PT zone was 46.012%

The effective field percentage of Team B in the NC3 zone was 54.688%

The effective field percentage of Team B in the C3 zone was 35.714%

In [25]:
!jupyter nbconvert --to script config_template.ipynb

This application is used to convert notebook files (*.ipynb) to various other
formats.

WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.

Options
=======
The options below are convenience aliases to configurable class-options,
as listed in the "Equivalent to" description-line of the aliases.
To see all configurable class-options for some <cmd>, use:
    <cmd> --help-all

[NbConvertApp] WARNING | pattern 'config_template.ipynb' matched no files

--debug
    set log level to logging.DEBUG (maximize logging output)
    Equivalent to: [--Application.log_level=10]
--generate-config
    generate default config file
    Equivalent to: [--JupyterApp.generate_config=True]
-y
    Answer yes to any questions instead of prompting.
    Equivalent to: [--JupyterApp.answer_yes=True]
--execute
    Execute the notebook prior to export.
    Equivalent to: [--ExecutePreprocessor.enabled=True]
--allow-errors
    Continue notebook execution even if one of the cells throws an error and include the error message in the cell output (the default behaviour is to abort conversion). This flag is only relevant if '--execute' was specified, too.
    Equivalent to: [--ExecutePreprocessor.allow_errors=True]
--stdin
    read a single notebook file from stdin. Write the resulting notebook with default basename 'notebook.*'
    Equivalent to: [--NbConvertApp.from_stdin=True]
--stdout
    Write notebook output to stdout instead of files.
    Equivalent to: [--NbConvertApp.writer_class=StdoutWriter]
--inplace
    Run nbconvert in place, overwriting the existing notebook (only
    relevant when converting to notebook format)
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory=]
--clear-output
    Clear output of current file and save in place,
    overwriting the existing notebook.
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --ClearOutputPreprocessor.enabled=True]
--no-prompt
    Exclude input and output prompts from converted document.
    Equivalent to: [--TemplateExporter.exclude_input_prompt=True --TemplateExporter.exclude_output_prompt=True]
--no-input
    Exclude input cells and output prompts from converted document.
    This mode is ideal for generating code-free reports.
    Equivalent to: [--TemplateExporter.exclude_output_prompt=True --TemplateExporter.exclude_input=True --TemplateExporter.exclude_input_prompt=True]
--allow-chromium-download
    Whether to allow downloading chromium if no suitable version is found on the system.
    Equivalent to: [--WebPDFExporter.allow_chromium_download=True]
--log-level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
    Equivalent to: [--Application.log_level]
--config=<Unicode>
    Full path of a config file.
    Default: ''
    Equivalent to: [--JupyterApp.config_file]
--to=<Unicode>
    The export format to be used, either one of the built-in formats
    ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf',
    'python', 'rst', 'script', 'slides', 'webpdf'] or a dotted object name that
    represents the import path for an ``Exporter`` class
    Default: ''
    Equivalent to: [--NbConvertApp.export_format]
--template=<Unicode>
    Name of the template to use
    Default: ''
    Equivalent to: [--TemplateExporter.template_name]
--template-file=<Unicode>
    Name of the template file to use
    Default: None
    Equivalent to: [--TemplateExporter.template_file]
--writer=<DottedObjectName>
    Writer class used to write the  results of the conversion
    Default: 'FilesWriter'
    Equivalent to: [--NbConvertApp.writer_class]
--post=<DottedOrNone>
    PostProcessor class used to write the results of the conversion
    Default: ''
    Equivalent to: [--NbConvertApp.postprocessor_class]
--output=<Unicode>
    overwrite base name use for output files. can only be used when converting
    one notebook at a time.
    Default: ''
    Equivalent to: [--NbConvertApp.output_base]
--output-dir=<Unicode>
    Directory to write output(s) to. Defaults to output to the directory of each
    notebook. To recover previous default behaviour (outputting to the current
    working directory) use . as the flag value.
    Default: ''
    Equivalent to: [--FilesWriter.build_directory]
--reveal-prefix=<Unicode>
    The URL prefix for reveal.js (version 3.x). This defaults to the reveal CDN,
    but can be any url pointing to a copy  of reveal.js.
    For speaker notes to work, this must be a relative path to a local  copy of
    reveal.js: e.g., "reveal.js".
    If a relative path is given, it must be a subdirectory of the current
    directory (from which the server is run).
    See the usage documentation
    (https://nbconvert.readthedocs.io/en/latest/usage.html#reveal-js-html-
    slideshow) for more details.
    Default: ''
    Equivalent to: [--SlidesExporter.reveal_url_prefix]
--nbformat=<Enum>
    The nbformat version to write. Use this to downgrade notebooks.
    Choices: any of [1, 2, 3, 4]
    Default: 4
    Equivalent to: [--NotebookExporter.nbformat_version]

Examples
--------

    The simplest way to use nbconvert is

    > jupyter nbconvert mynotebook.ipynb --to html

    Options include ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'rst', 'script', 'slides', 'webpdf'].

    > jupyter nbconvert --to latex mynotebook.ipynb

    Both HTML and LaTeX support multiple output templates. LaTeX includes
    'base', 'article' and 'report'.  HTML includes 'basic' and 'full'. You
    can specify the flavor of the format used.

    > jupyter nbconvert --to html --template lab mynotebook.ipynb

    You can also pipe the output to stdout, rather than a file

    > jupyter nbconvert mynotebook.ipynb --stdout

    PDF is generated via latex

    > jupyter nbconvert mynotebook.ipynb --to pdf

    You can get (and serve) a Reveal.js-powered slideshow

    > jupyter nbconvert myslides.ipynb --to slides --post serve

    Multiple notebooks can be given at the command line in a couple of
    different ways:

    > jupyter nbconvert notebook*.ipynb
    > jupyter nbconvert notebook1.ipynb notebook2.ipynb

    or you can specify the notebooks list in a config file, containing::

        c.NbConvertApp.notebooks = ["my_notebook.ipynb"]

    > jupyter nbconvert --config mycfg.py

To see all available configurables, use `--help-all`.